### ISSUE TITLE
https://myvariant.info/v1/variant/rs13328684 is list instead of normal json

### ISSUE THREAD

**Issue by hopdebee** [biothings/myvariant.info#74]
Hey, 

First, awesome work ! 

Second:

https://myvariant.info/v1/variant/rs13328684 gives a list. All rs-id's i tested give normal Json output, starting with {

Is this a bug ? 

Thanks !

**Comment by kevinxin90** [comment]
Hi,

This is not a bug.

Sometimes an rs-id can correspond to multiple variants, which is the case here. You can refer to the dbsnp website at https://www.ncbi.nlm.nih.gov/snp/rs13328684. This rs-id corresond to 3 different variants.

In MyVariant.info, the primary ID we use is HGVS ID, which is determined by chrom, ref, alt and position. We don't merge documents based on rs-id. That's why when you query for this rs-id, it will return a list of JSON documents (each document representing a variant).
